albums_xml_simple = {"xmlns"=>"http://www.w3.org/2005/Atom",
    "xmlns:app"=>"http://www.w3.org/2007/app",
    "xmlns:gphoto"=>"http://schemas.google.com/photos/2007",
    "xmlns:media"=>"http://search.yahoo.com/mrss/",
    "xmlns:openSearch"=>"http://a9.com/-/spec/opensearch/1.1/",
    "xmlns:gd"=>"http://schemas.google.com/g/2005",
    "xmlns:gml"=>"http://www.opengis.net/gml",
    "xmlns:georss"=>"http://www.georss.org/georss",
    "gd:etag"=>"W/\"CkYDSHszeCp7ImA9WhNXEEk.\"",
    "id"=>"https://picasaweb.google.com/data/feed/user/2544554",
    "updated"=>"2012-11-27T18:16:19.580Z",
    "category"=>
      {"scheme"=>"http://schemas.google.com/g/2005#kind",
      "term"=>"http://schemas.google.com/photos/2007#user"},
    "title"=>"2544554",
    "subtitle"=>{},
    "icon"=>
    "https://lh3.googleusercontent.com/-AAAAA/JHKHKHK/ASFDASD/GTDG/s64-c/453456345345.jpg",
    "link"=>
      [{"rel"=>"http://schemas.google.com/g/2005#feed",
      "type"=>"application/atom+xml",
      "href"=>
      "https://picasaweb.google.com/data/feed/api/user/3543454"},
      {"rel"=>"http://schemas.google.com/g/2005#post",
      "type"=>"application/atom+xml",
      "href"=>
      "https://picasaweb.google.com/data/feed/api/user/3465656"},
      {"rel"=>"alternate",
      "type"=>"text/html",
      "href"=>"https://picasaweb.google.com/356546546"},
      {"rel"=>"http://schemas.google.com/photos/2007#slideshow",
      "type"=>"application/x-shockwave-flash",
      "href"=>
      "https://picasaweb.google.com/s/c/bin/slideshow.swf?host=picasaweb.google.com&RGB=0x000000&feed=https%3A%2F%2Fpicasaweb.google.com%2Fdata%2Ffeed%2Fapi%2Fuser%2F34534545%3Falt%3Drss"},
      {"rel"=>"self",
      "type"=>"application/atom+xml",
      "href"=>
      "https://picasaweb.google.com/data/feed/api/user/345345?start-index=1&max-results=1000"}],
    "author"=>
      {"name"=>"Rspec Test",
      "uri"=>"https://picasaweb.google.com/34534534"},
    "generator"=>
      {"version"=>"1.00",
      "uri"=>"http://picasaweb.google.com/",
      "content"=>"Picasaweb"},
    "totalResults"=>"2",
    "startIndex"=>"1",
    "itemsPerPage"=>"1000",
    "user"=>"6345345",
    "nickname"=>"Rspec Test",
    "thumbnail"=>
      "https://lh3.googleusercontent.com/-AAAAA/JHKHKHK/ASFDASD/GTDG/s64-c/17820945109299503.jpg",
    "quotalimit"=>"1073741824",
    "quotacurrent"=>"145916427",
    "maxPhotosPerAlbum"=>"1000",
    "entry"=>[
      {"gd:etag"=>"\"OIGkkI.\"",
      "id"=>
        ["https://picasaweb.google.com/data/entry/user/345345/albumid/345345345345345",
        "53453453454"],
      "published"=>"2012-10-23T21:03:52.000Z",
      "updated"=>"2012-11-12T22:45:05.275Z",
      "edited"=>"2012-11-12T22:45:05.275Z",
      "category"=>
        {"scheme"=>"http://schemas.google.com/g/2005#kind",
        "term"=>"http://schemas.google.com/photos/2007#album"},
      "title"=>"Rspec photos",
      "summary"=>"Rspec photos album",
      "rights"=>"public",
      "link"=>
        [{"rel"=>"http://schemas.google.com/g/2005#feed",
        "type"=>"application/atom+xml",
        "href"=>
        "https://picasaweb.google.com/data/feed/api/user/345345345/albumid/34534534"},
        {"rel"=>"alternate",
        "type"=>"text/html",
        "href"=>
        "https://picasaweb.google.com/3453456345/ProfilePhotos"},
        {"rel"=>"self",
        "type"=>"application/atom+xml",
        "href"=>
        "https://picasaweb.google.com/data/entry/api/user/35345/albumid/3453454"},
        {"rel"=>"edit",
        "type"=>"application/atom+xml",
        "href"=>
        "https://picasaweb.google.com/data/entry/api/user/453454/albumid/345345"},
        {"rel"=>"http://schemas.google.com/acl/2007#accessControlList",
        "type"=>"application/atom+xml",
        "href"=>
        "https://picasaweb.google.com/data/entry/api/user/345345/albumid/345345/acl"}],
      "author"=>
        {"name"=>"Rspec Test",
        "uri"=>"https://picasaweb.google.com/345345345"},
      "name"=>"ProfilePhotos",
      "location"=>{},
      "access"=>"public",
      "timestamp"=>"1351026232000",
      "numphotos"=>"2",
      "numphotosremaining"=>"998",
      "bytesUsed"=>"69840",
      "user"=>"56546546",
      "nickname"=>"Rspec Test",
      "albumType"=>"ProfilePhotos",
      "group"=>
        {"content"=>
        {"url"=>
        "https://lh3.googleusercontent.com/-AAAAA/JHKHKHK/ASFDASD/GTDG/s64-c/RspecPhotos.jpg",
        "type"=>"image/jpeg",
        "medium"=>"image"},
        "credit"=>"Rspec Test",
        "description"=>{"type"=>"plain"},
        "keywords"=>{},
        "thumbnail"=>
        {"url"=>
        "https://lh6.googleusercontent.com/-AAAAA/JHKHKHK/ASFDASD/GTDG/s64-c/RspecPhotos.jpg",
        "height"=>"160",
        "width"=>"160"},
        "title"=>{"type"=>"plain", "content"=>"Rspec photos"}}},

      {"gd:etag"=>"\"YDsqeyI.\"",
      "id"=>
        ["https://picasaweb.google.com/data/entry/user/345345/albumid/345345",
        "345345"],
      "published"=>"2012-08-19T07:00:00.000Z",
      "updated"=>"2012-08-19T09:10:31.843Z",
      "edited"=>"2012-08-19T09:10:31.843Z",
      "category"=>
        {"scheme"=>"http://schemas.google.com/g/2005#kind",
        "term"=>"http://schemas.google.com/photos/2007#album"},
      "title"=>"BCM94322",
      "summary"=>{},
      "rights"=>"private",
      "link"=>
        [{"rel"=>"http://schemas.google.com/g/2005#feed",
        "type"=>"application/atom+xml",
        "href"=>
        "https://picasaweb.google.com/data/feed/api/user/345345/albumid/35345?authkey=adfasKHJKHADFkf"},
        {"rel"=>"alternate",
        "type"=>"text/html",
        "href"=>
        "https://picasaweb.google.com/5345345/BCM94322?authkey=adfasdfdsLHKJHKHasdf"},
        {"rel"=>"self",
        "type"=>"application/atom+xml",
        "href"=>
        "https://picasaweb.google.com/data/entry/api/user/3453454/albumid/345343?authkey=asdfFDFASFSdasd"},
        {"rel"=>"edit",
        "type"=>"application/atom+xml",
        "href"=>
        "https://picasaweb.google.com/data/entry/api/user/35345/albumid/345345?authkey=Gv1sRgCasdfasdfFDAFE"},
        {"rel"=>"http://schemas.google.com/acl/2007#accessControlList",
        "type"=>"application/atom+xml",
        "href"=>
        "https://picasaweb.google.com/data/entry/api/user/45345345/albumid/345345/acl?authkey=Gv1sRgCASFADSE"}],
      "author"=>
        {"name"=>"Rspec Test",
        "uri"=>"https://picasaweb.google.com/3456345"},
      "name"=>"BCM94322",
      "location"=>{},
      "access"=>"private",
      "timestamp"=>"1345359600000",
      "numphotos"=>"2",
      "numphotosremaining"=>"998",
      "bytesUsed"=>"3949662",
      "user"=>"345345",
      "nickname"=>"Rspec Test",
      "group"=>
        {"content"=>
        {"url"=>
          "https://lh6.googleusercontent.com/-AAAAA/JHKHKHK/ASFDASD/GTDG/s64-c/nnmvPeC92o/BCM94322.jpg",
          "type"=>"image/jpeg",
          "medium"=>"image"},
          "credit"=>"Rspec Test",
          "description"=>{"type"=>"plain"},
          "keywords"=>{},
          "thumbnail"=>
            {"url"=>
            "https://lh6.googleusercontent.com/-AAAAA/JHKHKHK/ASFDASD/GTDG/s64-c/BCM94322.jpg",
            "height"=>"160",
            "width"=>"160"},
          "title"=>{"type"=>"plain", "content"=>"BCM94322"}
        }
      }
    ]
}